---
- name: configure yum/dnf repo
  copy: >
    src=kibana.repo
    dest=/etc/yum.repos.d/kibana.repo
    owner=root
    group=root
    mode=0644
  register: updated_sources

- name: install kibana
  package: >
    name="{{item}}"
    state=latest
  with_items:
    - "{{elk_java_package}}"
    - kibana

- name: configure kibana
  lineinfile: >
    line={{item}}
    dest=/opt/kibana/config/kibana.yml
    state=present
  with_items:
    - "server.port: {{kibana_port}}"
    - "server.host: {{kibana_host}}"
    - "elasticsearch.url: \"{{kibana_elasticsearch_url}}\""

- name: enable kibana start up
  service: >
    name={{kibana_service_name}}
    enabled=yes
    state=started
  notify: restart kibana
